### PR TITLE
[ADVAPP-720]: Enhance the display of employee information for user administrators by displaying the team they are on.

### PR DESCRIPTION
**Pull request by payal-canyon**
### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-720

### Technical Description

> Add a new column for Team with a default off status that can be turned on.

### Any deployment steps required?

> No

### Are any Feature Flags Added?

> No

_______________________________________________

### CODE REVIEW

**Comment by payal-canyon** [comment]
> ### Ticket(s) or GitHub Issue
> * https://canyongbs.atlassian.net/browse/ADVAPP-720
> 
> ### Technical Description
> > Add a new column for Team with a default off status that can be turned on.
> 
> ### Any deployment steps required?
> > No
> 
> ### Are any Feature Flags Added?
> > No
> 
> #### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/advisingapp/blob/main/README.md#contributing).

Note: Commented the limit() function in teams relation under the User model, causing issues in displaying team name on the User Management page. It only displays the team name for the first user. Let me know, If I need to add another relation for it.

**Comment by payal-canyon** [comment]
Hi @Orrison 
I Commented the limit() function in teams relation under the User model, causing issues in displaying team name on the User Management page. It only displays the team name for the first user. Let me know, If I need to add another relation for it.

**Comment by Orrison** [comment]
> Hi @Orrison I Commented the limit() function in teams relation under the User model, causing issues in displaying team name on the User Management page. It only displays the team name for the first user. Let me know, If I need to add another relation for it.

@payal-canyon to confirm, is the issue that it seems to cause only the first User in the list to have Team displayed? Or that it only shows the first Team assigned to each User?

**Comment by payal-canyon** [comment]
> > Hi @Orrison I Commented the limit() function in teams relation under the User model, causing issues in displaying team name on the User Management page. It only displays the team name for the first user. Let me know, If I need to add another relation for it.
> 
> @payal-canyon to confirm, is the issue that it seems to cause only the first User in the list to have Team displayed? Or that it only shows the first Team assigned to each User?

Hi @Orrison,
No! Actually when displaying the team name on the list user page then for first-row only the team name is displayed. Therefore, I need to comment out the limit() function, and once I commented for each row team name is displayed.

**Comment by Orrison** [comment]
> > > Hi @Orrison I Commented the limit() function in teams relation under the User model, causing issues in displaying team name on the User Management page. It only displays the team name for the first user. Let me know, If I need to add another relation for it.
> > 
> > 
> > @payal-canyon to confirm, is the issue that it seems to cause only the first User in the list to have Team displayed? Or that it only shows the first Team assigned to each User?
> 
> Hi @Orrison, No! Actually when displaying the team name on the list user page then for first-row only the team name is displayed. Therefore, I need to comment out the limit() function, and once I commented for each row team name is displayed.

Interesting... go ahead and just remove the limit for now (no need to leave the commented out code) and I will create a ticket to address this later

**Review by Orrison — APPROVED** [review]

**Pull request merged**
