### PR TITLE
[ADVAPP-838]: When uploading a partner logo of the PNG type the logo renders with distorted proportions.

### PR DESCRIPTION
**Pull request by jayushi-canyon**
### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-838

### Technical Description

> Set static position for header logo.

### Any deployment steps required?

> No.

### Are any Feature Flags Added?

> No.

_______________________________________________

### CODE REVIEW

**Review by Orrison — CHANGES_REQUESTED** [review]
@jayushi-canyon you may be right here, but can you explain your reasoning behind adding the `w-56`.

This does need to work for any kind of logo uploaded in the future and I am just concerned that this with was added to possibly be specific to the example image.

The goal is to ensure that no matter what is uploaded that the aspect ration of the image is preserved so the image does not look distorted.

Perhaps we need something like a max width or perhaps a max height? And just let the width size accordingly.

@danharrin if you can weight in as well.

**Comment by jayushi-canyon** [comment]
> @jayushi-canyon you may be right here, but can you explain your reasoning behind adding the `w-56`.
> 
> This does need to work for any kind of logo uploaded in the future and I am just concerned that this with was added to possibly be specific to the example image.
> 
> The goal is to ensure that no matter what is uploaded that the aspect ration of the image is preserved so the image does not look distorted.
> 
> Perhaps we need something like a max width or perhaps a max height? And just let the width size accordingly.
> 
> @danharrin if you can weight in as well.

I kept w-52, by considering that when any image is uploaded for the logo, It will always be the same width for any image.

**Comment by jayushi-canyon** [comment]
> > > @jayushi-canyon you may be right here, but can you explain your reasoning behind adding the `w-56`.
> > > This does need to work for any kind of logo uploaded in the future and I am just concerned that this with was added to possibly be specific to the example image.
> > > The goal is to ensure that no matter what is uploaded that the aspect ration of the image is preserved so the image does not look distorted.
> > > Perhaps we need something like a max width or perhaps a max height? And just let the width size accordingly.
> > > @danharrin if you can weight in as well.
> > 
> > 
> > @Orrison I kept w-52, by considering that when any image is uploaded for the logo, It will always be the same width for any image.
> 
> Got it. Hmm but I don't think we want to force both dimensions on the image as that will not enforce the aspect ration of all logos.
> 
> Have you tried keeping the height as defined and then applying something like `w-auto`?

@Orrison Well rather than keeping w-auto, I think max-w-52 will make more sense as I tested the images with smaller width will not get distorted and one will larger will be set at w-52.

**Comment by danharrin** [comment]
Does `max-w-full` work instead to allow the width to be dynamic?

**Comment by jayushi-canyon** [comment]
> Does `max-w-full` work instead to allow the width to be dynamic?

@danharrin I think 'max-w-full' will create same issue as 'w-auto' as the images with larger width looks bigger with less padding where else I think as i have tested 'max-w-52' shows the logo with proper spacing, this would make sure no image goes beyond this pixel. What do you think?

**Comment by danharrin** [comment]
How about `h-full max-h-9 max-w-full`?

**Comment by jayushi-canyon** [comment]
> h-full max-h-9 max-w-full

@danharrin  I tested this classes with 3 different images :
Screenshot 2024-09-04 212316
Screenshot 2024-09-04 212327
Screenshot 2024-09-04 212341

**Comment by danharrin** [comment]
That looks good to me, what do you think?

**Review by Orrison — APPROVED** [review]

**Pull request merged**
