### PR TITLE
[ADVAPP-592] Footer sticky issue fix in assistant page

### PR DESCRIPTION
**Pull request by ankit-canyon**
### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/ADVAPP-592

### Technical Description

> Describe your changes in detail. This should include technical/architectural decisions and reasoning, if applicable.
> Removed the classes "h-screen max-h-[calc(100dvh-20rem)]" that creating issue for sticky footer in assistant page.

_______________________________________________

### CODE REVIEW

**Review by Orrison — CHANGES_REQUESTED** [review]
As we discussed in Sprint/Tech Planning, please ensure that this does not break that the AI chat window should vertically fill the page, even when no messages have been sent.

Also confirm whether or not this fixes the other display issues. Let me know here if so on either.

**Comment by ankit-canyon** [comment]
> Member

Hi,

Yes it will look like this when there is no chat. 

image

Also it fixes the display issue described in [ADVAPP-611].

Thank you.

**Review by Orrison — CHANGES_REQUESTED** [review]
@ankit-canyon I merged this together with 611. Let's go ahead and fix both issues here in this same PR.

This is looking good on mobile now, but removing the classes does now cause the chat to no longer be at the bottom of the page. And so as you added messages to the chat, the chat window grows in length and moves in position till it is off the page.

We need this fixed so the chat window always fills the size of the screen and does not move as the conversation grows. While also still looking correct on mobile.

Perhaps we need to bring the classes back but add a media query like `lg:` to the classes or something like that?

**Comment by Orrison** [comment]
https://github.com/canyongbs/advisingapp/assets/6799341/f0645486-c0c6-45b4-b8b8-52d0618a3cf3

**Review by Orrison — APPROVED** [review]

**Pull request merged**
